package project.io.app.core.user.exception;

public class UserNotFoundException extends RuntimeException {
}
